### ISSUE TITLE
Which model gets the backref?

### ISSUE THREAD

**Issue by Matt-Eva** [learn-co-curriculum/python-p3-sqlalchemy-one-to-many#3]
### Canvas Link

https://learning.flatironschool.com/courses/6049/assignments/208545?module_item_id=480724

### Concern

In the first example of one-to-many and one-to-one relationships, the one-to-many model shows the backref being placed on the model that does not have the foreign key - i.e. the model that "has_many" resources from the other table. In the one-to-one model, the backref and the foreign key are placed upon the same model. Is one of these a mistake?

Also, just to make sure I understand backref correctly, it's what allows us to collect order data associated with a single customer from the orders table, correct? Without it, we'd only be able to grab a single customer from the customer table associated with a specific order, right?

Also I noticed that in some circumstances, when creating foreign keys, we use plural to refer to the data we want to get the id from:
```
customer_id = Column(Integer(), ForeignKey("customers.id"))
```
where in other cases we use singular:
```
order_id = Column(Integer(), ForeignKey("order.id"))
```
Does this have to do with one-to-one or one-to-many relationships? Or is one of these a mistake?

Thanks!

**Comment by professor-ben** [comment]
The ForeignKey piece was a mistake. It should always use the tablename- plural.

The `backref` should always go onto a model that has many of the other side. I would rather write this rule as the "one" though, because `backref` should be avoided in favor of `back_populates` in the many-to-many case.

These changes and a few others should be visible now!

**Comment by Matt-Eva** [comment]
Awesome, thank you Ben!
